// ES6 module syntax
import LocalizedStrings from "react-localization";

let strings = new LocalizedStrings({
  en: {
    newPost: "New Post",
    topPosts: "Top Posts",
    socialNetwork: "Social Network",
    partyNews: "Party News",
    newsletters: "Newsletters",
    trandyPosts: "Trandy Posts",
    popular: "Popular",
    show: "Show",
    movies: "Movies",
    reports: "Reports",
    keys: "Keys",
    music: "Music",
    subscriptions: "Subscriptions",
    news: "News",
    fashion: "Fashion",
    events: "Events", 
    sports: "Sports",
    lifestyle: "Lifestyle",
    addImage: "Add Image",
    explanation: "Explanation",
    title: "Title",
    addTags: "Add Tags",
    addFlag: "Add Flag",
    sendPost: "Send Post",
    sendVideo: "Send Video",
    uploadOrDropFile: "Upload or drop a file right here",
    public: "Public",
    categories: "Categories",
    partyNewsContent:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Egestas purus viverra accumsan in nisi nisi. Arcu cursus vitae congue mauris rhoncus aenean vel elit scelerisque. In egestas erat imperdiet sed euismod nisi porta lorem mollis. Morbi tristique senectus et netus. Mattis pellentesque id nibh tortor id aliquet lectus proin.",
    newslettersPlaceholder: "Enter your email here",
    privacyPolicy: "Privacy Policy",
    termsAndConditions: "Terms & Conditions",
    allRightsReserved: "All rights reserved",
    aboutUsComponentHeading1:
      "Ние обръщаме внимание на вашите нужди и правим най-добрия дизайн.",
    aboutUsComponentData1:"Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Egestas purus viverra accumsan in nisi nisi. Arcu cursus vitae congue mauris rhoncus aenean vel elit scelerisque. In egestas erat imperdiet sed euismod nisi porta lorem mollis. Morbi tristique senectus et netus. Mattis pellentesque id nibh tortor id aliquet lectus proin.",
  },
  bg: {
    newPost: "Нова публикация",
    topPosts: "Топ публикации",
    socialNetwork: "Социална мрежа",
    partyNews: "Партийни новини",
    newsletters: "Бюлетини",
    trandyPosts: "Тенденции",
    popular: "Популярни",
    show: "Шоу",
    movies: "Филми",
    reports: "Репортажи",
    keys: "Ключове",
    music: "Музика",
    subscriptions: "Абонаменти",
    news: "Новини",
    fashion: "Мода",
    events: "Събития",
    sports: "Спорт",
    lifestyle: "Лайфстайл",
    addImage: "Добавяне на изображение",
    explanation: "Обяснение",
    title: "Заглавие",
    addTags: "Добавяне на етикети",
    addFlag: "Добавяне на флаг",
    sendPost: "Изпрати публикация",
    sendVideo: "Изпрати видео",
    uploadOrDropFile: "Качете или пуснете файл тук",
    public: "Публичен",
    categories: "Категории",
    partyNewsContent:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Еgestas purus viverra accumsan in nisi nisi. Arcu cursus vitae congue mauris rhoncus aenean vel elit scelerisque. In egestas erat imperdiet sed euismod nisi porta lorem mollis. Morbi tristique senectus et netus. Mattis pellentesque id nibh tortor id aliquet lectus proin.",
    newslettersPlaceholder: "Напишете имейл си",
    privacyPolicy: "Политика за поверителност",
    termsAndConditions: "Условия за ползване",
    allRightsReserved: "Всички права запазени",
  },
});

export default strings;
